### ISSUE TITLE
Standardize pulse amplitude meaning

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#1006]
The initial idea in 0.1 was that amplitude is dimensionless in [-1, 1]. However, when I implemented the QM driver, I treated it as raw voltage, essentially limiting it to [-0.5, 0.5] as per instrument specifications. 

We should properly define its meaning for 0.2, as this is essentially part of the interface, and update the QM driver accordingly, so that all instruments behave consistently in the future. The update should be easy, for QM it should be sufficient to divide all waveform samples by 2 before uploading to the instrument.

@alecandido @andrea-pasquale in case you are interested and have any suggestion.

**Comment by andrea-pasquale** [comment]
For sure it would be interested to map the amplitude to volts. I'm in favour of standardizing everything between [-1,1] and later think about a way to map this dimensionless quantity to something measurable (like volts).
For characterization purposes, at least when dealing with flux pulses it might be more interesting to map the amplitude directly to the detuning on the qubit frequency (I'm currently working on something like this).
