### ISSUE TITLE
`AcquireChannel` and `AcquisitionConfig`

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#1032]
While updating the docs I noticed that we have an `AcquireChannel` and the corresponding `AcquisitionConfig`.

That is fine for me, however I think it would be easier for users if, at least interface objects, have more consistent names. @alecandido let me know what you think.

**Comment by alecandido** [comment]
`AcquisitionChannel` should be fine.

It's not strictly a priority, but it will be part of the interface, so we can make it consistent before freezing.

**Comment by stavros11** [comment]
Fixed by #1035.
