### ISSUE TITLE
Identity gate to sequence error

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibolab#108]
@scarrazza @stavros11 @aorgazf I have found a small bug. It is raised when a sequence of gates starts with the Identity gate. 
As it is implemented in qibo the metjod to_sequence od the Identity gate produces an illegal state on the sequencer when it is the firts gate to be executed in a sequence (not when it is in the middle, because the sequencer has been inicialized with a valid pulseSequence in a previous stage of the sequence).

This error is not raised when you translate the "I" gate as it is done in the PR #107 with pulses, creating a pulse with 0 amplitude for the "I" gate. 

Can you review the gate translation in Qibo?

**Comment by scarrazza** [comment]
Shall we close this?

**Comment by DavidSarlle** [comment]
the problem was fixed some time ago. We can close the issue.
