### ISSUE TITLE
Output post processing and shots

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#124]
Related issue #63. When we execute a pulse sequence or a circuit we obtain a readout dictionary that looks like
```
{0: {"ReadoutPulse(142, 2000, 0.900, 20000000, 3.142, 'Rectangular()', 10, 'ro')": (0.0017713258742787735, 1.9431535617144184, -0.0006444298566706158, 0.0016499410634083118)}}
```
A theory user would probably like to extract some of the following:
1. Raw measurement shots as bitstrings,
2. Measurement frequency from each bitstring (can be calculated from 1),
3. Probabilities for each bitstring (can be calculated naively from 2, unless there is a more sophisticated procedure that uses the readout voltages directly).

The number of shots that are returned should be what the user specifies as `nshots` when executing the circuit. Eg. if the user asks for 1000 shots he should get back 1000 bitstrings, not a single average voltage.

@DavidSarlle is this implemented in any branch of the code?

**Comment by scarrazza** [comment]
Shall we close this?

**Comment by stavros11** [comment]
This is about single shot measurements so I would keep it open since it is not addressed in main. I will link it to #195 which is implementing this.
