### ISSUE TITLE
platform attributes confusion

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibolab#147]
Hi, 

The platform has some attributes like `platform.ro_port[qubit].lo_freq` which don't change the frequency. It got us confuse to why it was not working. We had to use `platform.ro_port[qubit].lo_frequency` . 
I don't know what `platform.ro_port[qubit].lo_freq` is being used for but maybe it could become private (platform.ro_port[qubit]._lo_freq`.  

@aorgazf

**Comment by scarrazza** [comment]
Closing in favor of #208
