### ISSUE TITLE
Automatic port selection for qq-live

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibolab#202]
As the title says, we should at least crash if the port is being used.

**Comment by andrea-pasquale** [comment]
@scarrazza now for qq-live we already have an automatic port selection mechanism.
If the port it is already used qq-live will check if the next port it is used and it will continue until he finds a port which is available.
See for example here:
https://github.com/qiboteam/qibocal/blob/97550347244aafe9115c75ce4c0c4b29d1cfa029/src/qibocal/cli/_base.py#L78-L82
Is this enough or do you prefer that we simply crash if the port is being used?

**Comment by scarrazza** [comment]
Perfect, thanks for pointing this out, I have probably see a testcase with an old qq-live version.

**Comment by stavros11** [comment]
Just pointing out that some people had issues with this mechanism. In some cases the loop checking for available ports was hanging and qq-live was never executed. The quick solution I proposed was to use the -port argument to skip the port that was causing the hanging, but I have not checked in detail the issue. There may be a more robust way to select the port automatically.

**Comment by scarrazza** [comment]
Right, I believe this problem still there. The code should not hang but at least raise an error saying the port is not available.

**Comment by scarrazza** [comment]
@andrea-pasquale shall we close this?

**Comment by andrea-pasquale** [comment]
Yeah, I think so @scarrazza. The user can always select a specific port if there are some issues as @stavros11 pointed out.
