### ISSUE TITLE
Modify qblox driver to expose port offsets

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibolab#227]
We believe it possible to bias qubits' flux with the dc offset of the qcm modules. This offset persists between pulse sequence executions.
For the sake of simplicity, the driver did not expose the offset property as it was not being used up until now.
We now want to modify the driver to expose it.

**Comment by maxhant** [comment]
Hi @aorgazf, 
I believe that you have merged the baseband module with the current source here:
https://github.com/qiboteam/qibolab/blob/5213ca867633330d0c14bbfefe8628ddd70ccc72/src/qibolab/platforms/abstract.py#L171
Any ideas on how to seperate them?
