### ISSUE TITLE
Improve setup syntax

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibolab#296]
Find a better way to spell out configurations:

https://github.com/qiboteam/qibolab/blob/9a3036ffcfc69d1532f96e2d6d23799029d4ee25/src/qibolab/platform.py#L70-L99

**Comment by AleCandido** [comment]
@stavros11 I guess we can close this now, isn't it?

The problem is now better isolated, and it is more a problem in `qibolab_platform_qrc`, from which we could extract successful solutions and import in Qibolab.
But I'd argue that it's not any longer a Qibolab issue in the first place.

**Comment by stavros11** [comment]
Yes, I agree.
