### ISSUE TITLE
Document and localize QM frequencies truncation 

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibolab#298]
According to https://github.com/qiboteam/qibolab/pull/291#discussion_r1097516223 QM requires integer frequencies.
This has to be documented, and, if possible, we should find a way to apply this integer conversion in a single initial block for all the involved frequencies, such that if we do not risk to forget at a later stage.

**Comment by scarrazza** [comment]
Shall we close this issue?

**Comment by AleCandido** [comment]
Limiting internal conversions is still a relevant task (mainly to simplify the code), but I believe we should do it more consistently, this is a too specific issue, and if it survived is just a chance.
