### ISSUE TITLE
Cleanup platform object

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#304]
With the instrument design approach we should need only one `Platform` object which could also be a `@dataclass`.

_Originally posted by @AleCandido in https://github.com/qiboteam/qibolab/pull/259#discussion_r1066853968_
           
The options read by the runcard and particularly `platform.reload_settings` can also be cleaned up.

**Comment by AleCandido** [comment]
This has partially been done, and clean-up it's still work in progress #492. But I believe we don't need this is issue any longer.
