### ISSUE TITLE
Abstract specs for runcard settings and native gates

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#305]
_Originally posted by @AleCandido in https://github.com/qiboteam/qibolab/pull/259#discussion_r1066860261_

Also https://github.com/qiboteam/qibolab/pull/259#discussion_r1066861562

**Comment by AleCandido** [comment]
@stavros11 we should close even this one, correct?

**Comment by stavros11** [comment]
Yes, I think it was done by #387.
