### ISSUE TITLE
Stable documentation not rendered

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibolab#337]
The latest stable documentation is not visible at https://qibo.science/docs/qibolab/stable

**Comment by AleCandido** [comment]
From the artifact on this page https://github.com/qiboteam/qibolab/actions/runs/4454856014 I can tell it has been generated.
https://github.com/qiboteam/qibolab/suites/11649358645/artifacts/604995914

I'm not sure if it has ever been uploaded, since the actual website artifact is expired.
