### ISSUE TITLE
Rewrite transpiler

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibolab#360]
The current transpilers in `qibolab` are misleading with their naming of gates (for example the U3 decomposition is called a native gate, which it is not) and do not directly take into account the true native gates of a platform.

In the meeting with @igres26, @ingoroth and @stavros11 a new way of how to implement a better transpiler was discussed.
An arbitrary gate should be directly (or via a U3 decomposition) decomposed into its native gates.
When a circuit is constructed only with native gates, the transpiler would not do anything and the position (in time) of the native pulses could be highly controllable.

**Comment by AleCandido** [comment]
@wilkensJ is this still an issue in the current version of Qibolab? (i.e. with `main`)

**Comment by stavros11** [comment]
Now it is easier for the user to define their own transpiler, but the default transpiler is still using the U3 as the single qubit native gate. I am planning to change that to GPI and GPI2 which correspond to a single pulse so they are really native (because U3 corresponds to two pulses).

**Comment by stavros11** [comment]
Superseded by #606.
