### ISSUE TITLE
Sweeper with dependant parameters

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab#406]
This could be of use for the Ramsey Detuned routine where you are only sweeping the wait times but that will have on the wait times and the relative phase you need to apply on the second RX90 pulse. @stavros11 @rodolfocarobene  Have you already felt like this would be helpful for the implementation with QM or FPGAs ?

**Comment by stavros11** [comment]
Closing as duplicated by #650 and #692.
