### ISSUE TITLE
Add tests for circuits

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibolab#421]

**Comment by MatteoRobbiati** [comment]
> @MatteoRobbiati since you have experience with running circuits with Qibolab, could you take care of this?

Sure, what is needed is something like I did [here](https://github.com/qiboteam/qibolab/blob/67cf7bd09db2c006a49a98019338c33b059d69a9/tests/test_backends.py#L102)?

**Comment by AleCandido** [comment]
I just read the title and thought you were the best person. I guess for the exact request, you should ask @scarrazza.
