### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibolab#457]
From the last documentation deployment, you can see various warning and errors related to outdated components (new results, abstrac platform...)

https://github.com/qiboteam/qibolab/actions/runs/5109472801/jobs/9184821662#step:6:210

We should fix them, but also we may want to fix the workflow so that it fails when these kind of errors present (?)

**Comment by scarrazza** [comment]
We should update the README too.

**Comment by scarrazza** [comment]
For the next release we need proper documentation with examples and detailed updated explanations. @rodolfocarobene @Edoardo-Pedicillo could you please take care of this (and integrate the new figures from @MatteoRobbiati)?
