### ISSUE TITLE
Remove dependency on setuptools

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibolab#470]
Currently `qualang` depends on `dash` that has an undeclared dependency on `setuptools`, while waiting for a fix from `dash` (https://github.com/plotly/dash/issues/2557), we will add explicitly the dependency in `pyproject.toml`.

https://github.com/qiboteam/qibolab/blob/4767ca57306d40c6637541c44934bb5072213d3c/pyproject.toml#L35
https://github.com/qiboteam/qibolab/blob/4767ca57306d40c6637541c44934bb5072213d3c/pyproject.toml#L69

This issue is to remember us to remove it, when possible

**Comment by AleCandido** [comment]
https://github.com/plotly/dash/commit/2bb4f124147a0a0269bf5064e72c347812c4443d

**Comment by stavros11** [comment]
Not sure if it will fix this issue, but noting that I am also expecting newer releases for qm-qua and qualang_tools for fixing the py3.11 issue (#588). Hopefully we can resolve both then.

**Comment by stavros11** [comment]
setuptools is now a requirement for the latest versions of dash so I removed it from our requirements in #644.
