### ISSUE TITLE
Flexible backprop

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibolab#488]
All of this has a bunch of assumptions hard-coded:
- you start from the beginning
- every time that you go forward, you do fully, and then
- you also go backward right after

I would just play more at circuit level: just make a single `routing_step` on a single `Circuit`, and then provide some other functions to manipulate the circuit you pass:
- you can `.invert()` and concatenate (as done here)
- start from a different point
- take only gates that are close to the beginning
- and so on...

Essentially, you could just accept a function that takes your original circuit, and construct a derived circuit out of it, and then using the output circuit for the `routing_step`.
Of course, this output circuit should respect some conditions (like ending at the starting point), but you can describe the meaning and leave this up to the user.
You could provide the current function (back-and-forth-n-times) as a default value for the user manipulation function :)

_Originally posted by @AleCandido in https://github.com/qiboteam/qibolab/pull/439#discussion_r1226187204_

**Comment by Simone-Bordoni** [comment]
I think that passing the function to construct the circuit is an unrequired complication for the user, as everithing can be summarized in just one parameter, the numer of gates to be considered before the placing. I want ot construct a function that either takes the number of gates or the number of repetitions of the forward+backward steps
