### ISSUE TITLE
Interface for sequence unrolling

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab#494]
Regarding the interface, I was thinking to have a different method (for example `instrument.play_sequences` and `platform.execute_pulse_sequences`) for when passing the list of sequences, in contrast to `platform.execute_pulse_sequence` for a single sequence. What you did is also fine, it is just a bit more complicated when the same function behaves differently depending on the input type. Overall, personally I don't have a strong preference, let's see what others think.

_Originally posted by @stavros11 in https://github.com/qiboteam/qibolab/pull/493#pullrequestreview-1480318122_

**Comment by Jacfomg** [comment]
We agreed on using `execute_pulse_sequences`.

**Comment by Jacfomg** [comment]
@stavros11 this can be closed, right ?

**Comment by stavros11** [comment]
I think so, we have #427 for unrolling anyway.
