### ISSUE TITLE
classification probabilities wrong after LaboneQ update

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibolab#624]
Seems that after the last update of the ZH LabOneQ library the probabilities returned by the driver are swaped and the allXY is showing the 0 and 1 probabilities swaped. 

Example:
![image](https://github.com/qiboteam/qibolab/assets/39095664/9c95a8de-9d23-4ecf-b101-0fcd4906fc28)

Example from before:
![image](https://github.com/qiboteam/qibolab/assets/39095664/dacdaaf7-9dfa-4558-bc54-1808a4866a6a)

Testing qibocal with the qblox driver and qw5_gold the allXY and probabilities are working as expected, so I suppouse that is something introduced by ZH.

**Comment by Jacfomg** [comment]
Patch in #629
