### ISSUE TITLE
Improve sweep over duration Qblox

### ISSUE THREAD

**Issue by PiergiorgioButtarini** [qiboteam/qibolab#649]
It would be useful, e.g. for T1 routines, implementing the possibility of doing a larger sweep on the pulses duration in Qblox. 
Right now the maximum sweep should be 200ns.

**Comment by stavros11** [comment]
Just a small correction, I believe the affected routine from this is Rabi-length. T1 and T2 sweep delay, not duration, so in principle they should not be limited by memory.

**Comment by alecandido** [comment]
This is an internal improvement, it will be postponed to after 0.2.0.

**Comment by alecandido** [comment]
Specific to a certain refactoring arc. Now outdated.
