### ISSUE TITLE
SHFSG-RTR upgrade

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab#672]
Check if it is worth implementing or if it is included on our machines or requires purchase.
https://www.zhinst.com/ch/en/products/shfsg-rtr-output-router-and-adder

**Comment by alecandido** [comment]
For the time being, I'm not aware we need any further routing capability on Zurich.

Moreover, this is more of a hardware-specific issue (in the sense of the actual box in the lab). Thus, it is more QRC specific, rather than related to the Qibolab development.
