### ISSUE TITLE
Remove disconnected after circuit execution

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab#674]
I think you could send circuits in a faster way, comparable to sequence unrolling without memory issues, by just establishing a connection to the devices one at the beggining of the routine and disconnect whenever the qibocal routine ends, instead of just at the end of each circuit. At least, that may be an issue related to how I coded the Zurich driver.

**Comment by stavros11** [comment]
@Jacfomg could you please check again and see if this issue still exists? If yes can you provide an example, so that we can check.

**Comment by Jacfomg** [comment]
Okay, there is no reconnection between circuits neither among different routines as you said. So problem solved, my bad for not being updated on this.
