### ISSUE TITLE
Lift 'disconnect()' in 'ClusterModule'

### ISSUE THREAD

**Issue by PiergiorgioButtarini** [qiboteam/qibolab#749]
This is the exact same for QCM (RF and BB) and QRM, so you could lift these 5 lines to `ClusterModule`.

(I actually wonder why it was not here for the QRM before...)

_Originally posted by @AleCandido in https://github.com/qiboteam/qibolab/pull/740#discussion_r1450214131_

**Comment by alecandido** [comment]
Specific to a certain refactoring arc. Now outdated.
