### ISSUE TITLE
Zurich new relevant features

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab#795]
Laboneq 2.21.0
- Added the ability to sweep pulse amplitudes and frequencies in near-time for readout pulses

Laboneq 2.22.0
- OpenQASM things 
- An estimate of the total run time of a compiled experiment is now accessible through the estimated_runtime property of the CompiledExperiment object. Note that this is a best-case scenario estimate and disregards any communication overhead in the execution.
- Sweeping amplitude and intermediate frequency for integration weights in a near-time loop

Laboneq 2.23.0
- Nothing too relevant for us I think

Laboneq 2.24.0
- Labone release Release 24.01 @hay-k could you patch this one as well please ?
- Support for the pipeliner feature on SHFSG, SHFQA, SHFQC and HDAWG instruments. If your experiment is not properly executing due to resource limitations, e.g. too many sequencer instructions or too much waveform memory used, you can now add the chunk_count parameter to any single sweep in your experiment definition. The experiment will then be internally divided into a number of smaller subunits, which will be efficiently uploaded and executed on the instruments, bypassing many of the previous resource limitations

**Comment by alecandido** [comment]
@hay-k do we need this issue still open?

**Comment by alecandido** [comment]
I assume other `laboneq` releases happened in the meanwhile (the current latest version on PyPI is 2.33.1). This issue is definitely outdated.
