### ISSUE TITLE
Submodule of QrmRf as drive channel

### ISSUE THREAD

**Issue by PiergiorgioButtarini** [qiboteam/qibolab#805]
@PiergiorgioButtarini: in principle, we could make a minimal subclass making it clear that it is a qrm_rf used for this purpose.

However, I'd postpone after the `Module` reorganization, when the main class itself will be as minimal as possible.
In case you agree with the plan, just open an issue about this.

_Originally posted by @alecandido in https://github.com/qiboteam/qibolab/issues/800#issuecomment-1943390172_

**Comment by alecandido** [comment]
Specific to a certain refactoring arc. Now outdated.
