### ISSUE TITLE
Define qubit results

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#809]
Aren't you overwriting `results[acquisition.qubit]`?

`acquisition` is always the same for all `result` (outer loop), and then `acquisition.qubit` as well. Isn't it?

_Originally posted by @alecandido in https://github.com/qiboteam/qibolab/pull/738#discussion_r1494463241_
            
Currently `platform.execute_pulse_sequence` (and related execution methods) returns a dictionary that contains pulse serials and qubit names. If the sequence contains more than one readout per qubit, it is not well defined whether the qubit entries should contain all acquired measurements or only the ones from the latest readout pulse.

**Comment by alecandido** [comment]
The current proposal would be to have a flat dictionary, `dict[PulseId, npt.NDArray]` for the new unified `execute` method (defined in #861), with just the ids of the pulses, even when multiple sequences are passed.

E.g., if two sequences are passed, the resulting dictionary will have as keys the IDs of both sequences, the same that would be obtained by running them individually and merging the resulting dictionary.
