### ISSUE TITLE
Drop serialize properties in `qibolab.result`

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab#827]
While debugging https://github.com/qiboteam/qibocal/issues/737 I saw that `qibolab.result` still has some `serialize` properties that were originally used by qibocal. They have not been used in qibocal for a while now. 
If they were only used by qibocal I think that we should be able to drop them. 
Thoughts @alecandido @stavros11 @hay-k?

**Comment by alecandido** [comment]
Since it is just a matter of cleaning up, I postponed to 0.2.
