### ISSUE TITLE
Different signature of `execute_circuits`

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibolab#893]
The signature of `execute_circuits` 
https://github.com/qiboteam/qibolab/blob/483c5a541f5d8f67f2e561958544aff314a425c6/src/qibolab/backends.py#L112
is different from the abstract method in Qibo (see initial_state).
https://github.com/qiboteam/qibo/blob/703af36f06afff6dbc4a629a66b17671a8d8bd92/src/qibo/backends/abstract.py#L198-L200

**Comment by alecandido** [comment]
You're right regarding a missing `s` in `initial_states`. The different default instead is fine, the interface is compatible, it is not wrong that the meaning slightly change for the different implementors.
