### ISSUE TITLE
Circuit output object

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#9]
While writing some basic tests for the code I noticed the following: The `circuit.execute` method takes a `measurement_level` argument that controls the form of the outcome. Particularly:
* `measurement_level = 0` returns the raw data as they are returned from the scheduler after execution,
* `measurement_level = 1` does some kind of post-processing using `circuit._parse_result`,
* `measurement_level = 2` returns a `MeasurementResult` object that contains shots, similarly to when doing classical simulation with measurement gates and `nshots`.

All measurement levels start from the raw data and perform some kind of post-processing on it. The suggestion is to remove this functionality from the circuit and create a separate `Output` object to handle it. The circuit will always return this object which contains the raw data only and the user can then query this using different methods to obtain the level 1 or 2 results. This is more inline with simulation circuits that always return a state object containing the state and the user can get measurements using `result.samples()`, etc..

In addition, this way we can remove the `measurement_level` argument from `circuit.execute`, which creates a disagreement with the qibo simulator versions.

**Comment by scarrazza** [comment]
@stavros, shall we close?

**Comment by stavros11** [comment]
Yes, this is quite outdated and the result is the topic of other open issues and PRs.
