### ISSUE TITLE
Remove U3 compiler rule

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#928]
Related to https://github.com/qiboteam/qibolab/issues/927#issuecomment-2213704214, I would consider dropping the U3 from the default compiler and leaving GPI2 which should be sufficient to do any single-qubit gate. 

This is trivial and we could even do immediately, I would just prefer to postpone for 0.2 where we are breaking multiple things anyway.

**Comment by alecandido** [comment]
Agreed. But you can even open the PR immediately, just pointing to 0.2.

This does not even depend on any other ongoing development, so you can target https://github.com/qiboteam/qibolab/tree/0.2 directly.

**Comment by stavros11** [comment]
#929
