### ISSUE TITLE
Qubit object

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibolab#945]
Review the `Qubit` class, in the perspective of moving the characterization attributes (not related to execution) to Qibocal.

**Comment by andrea-pasquale** [comment]
This is fine also for me. We should discuss at some point on how to add those attributes to qibocal and even to `qibolab_platforms_qrc`, since I am expecting that people that are calibrating should push there some sort of information related to calibration.

**Comment by alecandido** [comment]
We will discuss the many facets of Qibocal update to Qibolab 0.2 (though @stavros11 is already doing part of it in https://github.com/qiboteam/qibocal/pull/809).

But first, let's finish 0.2 :)
(or just get closer to completion)
