### ISSUE TITLE
Unify instrument specific components

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#966]
As I said before, I believe that this could be non-driver-specific.
However, the implementation is very minimal, and with the current architecture is definitely needed. So, it is definitely fine for this PR.

But, having even seen the content of this, I'd try to take some time to attempt fully lifting components to the general Qibolab part.

(Specifically, the only bits that I believe are truly specific to QM in these components are the name of the attributes, the specific `port` layout - which can be converted - and the `serial` property, which could be just a function)

_Originally posted by @alecandido in https://github.com/qiboteam/qibolab/pull/933#discussion_r1706379557_

**Comment by alecandido** [comment]
This is now being addressed by #1001, since it was already convenient
